name: Deno Tauri Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno-tauri:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: '2.1.8'  # 使用你指定的 Deno 版本

    - name: Install GTK3 and related dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libsoup-3.0-common
        sudo apt-get install -y pkg-config libgtk-3-dev

    - name: Install Deno dependencies
      run: deno install

    - name: Run Tauri Dev
      run: deno task tauri dev
